name: PR Metrics

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y cloc jq

      - name: Get changed files
        run: |
          git fetch origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }}...HEAD > changed_files.txt

      - name: Run cloc on changed files
        run: |
          if [ -s changed_files.txt ]; then
            cloc --json --list-file=changed_files.txt > cloc.json
          else
            echo '{}' > cloc.json
          fi

      - name: Count added/removed lines
        run: |
          git diff --numstat origin/${{ github.base_ref }}...HEAD \
            | awk '{added+=$1; removed+=$2} END {print "{\"added\":"added",\"removed\":"removed"}"}' > diff.json

      - name: Merge metrics into final JSON
        run: |
          jq -s '.[0] * .[1]' cloc.json diff.json > metrics.json
          echo "Final metrics.json:"
          cat metrics.json

      - name: Send metrics to backend
        run: |
          curl -X POST https://your-backend.example.com/pr-metrics \
            -H "Content-Type: application/json" \
            -H "X-GitHub-PR: ${{ github.event.pull_request.number }}" \
            -d @metrics.json
